"""
Main script for processing raw data.

This script imports necessary functions from the services module and processes
the raw data stored in 'raw_data_c.json' when run as the main program.
"""

from services.data_services import *

if __name__ == '__main__':
    '''
    Usage:
    1. Crawl (if needed) and preprocess data from AOJ: 
        process_prepare_data()
        
    Result: 
        raw_data.json           Crawled data from AOJ, just read from this file if already crawled
                                11330 records
        preprocessed_data.json  Preprocess raw data
        literal_map_data.json   Mapping between distinct tokens to its encoded ID
    
    2. Split preprocessed data into train data and raw metrics data:
        process_split_data()
        
    Result:
        ac_data.json            Data only includes source code with status == 4 (accepted code)
        train_data.json         Data used to train the model
                                3501 records
        raw_metrics_data.json   (Unprocessed) data, used to run evaluation metrics
                                390 records

    3. Generate unprocessed data from accepted codes by prompting LLM
        process_generate_buggy_data()
        
    Result:
        raw_buggy_data.json     Unprocessed buggy data
                                each object contains judge_id (to map with the original source code) 
                                and its 5 buggy source codes which generated by LLM
                                
    4. 
    
    --------------------------------------------------------------------------------------------------------
    General information of preprocessed data:
        data = read_json_file('preprocessed_data.json')
        analyze_json_data(data)
    Result:
    - Total Objects: 10245
    - Status Count:
        Status 4: 3891
        Status 8: 1181
        Status 0: 1179
        Status 7: 618
        Status 2: 1026
        Status 1: 2347
        Status -1: 1
        Status 6: 2
    - Average Tokens: 111.91
    - Average Tokens (Status = 4): 102.77
    '''
    
    
    